# Generated by Django 5.2.7 on 2026-02-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vestoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('acao', 'Ação'), ('fii', 'FII'), ('renda_fixa', 'Renda Fixa'), ('cripto', 'Cripto'), ('outros', 'Outros')], max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=8, max_digits=18)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_compra', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
