# Generated by Django 5.2.7 on 2026-02-16 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vestoapp', '0002_investimento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investimento',
            old_name='nome',
            new_name='ativo',
        ),
        migrations.RenameField(
            model_name='investimento',
            old_name='data_compra',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='investimento',
            old_name='preco_unitario',
            new_name='valor_brl',
        ),
        migrations.AddField(
            model_name='investimento',
            name='preco_medio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='investimento',
            name='quantidade_usd',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='investimento',
            name='taxa',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='investimento',
            name='vencimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investimento',
            name='quantidade',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='investimento',
            name='tipo',
            field=models.CharField(choices=[('Renda Fixa', 'Renda Fixa'), ('Ação', 'Ação'), ('FII', 'FII'), ('Cripto', 'Cripto'), ('Dolar', 'Dolar')], max_length=20),
        ),
    ]
