# Generated by Django 6.0.4 on 2026-05-08 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vestoapp', '0003_rename_nome_investimento_ativo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Investimento',
        ),
        migrations.AddField(
            model_name='transacao',
            name='categoria',
            field=models.CharField(choices=[('alimentação', 'Alimentação'), ('transporte', 'Transporte'), ('moradia', 'Moradia'), ('saude', 'Saúde'), ('educacao', 'Educação'), ('lazer', 'Lazer'), ('investimentos', 'Investimentos'), ('salario', 'Salário'), ('vendas', 'Vendas'), ('outros', 'Outros')], default='outros', max_length=30),
        ),
    ]
