# Generated by Django 6.0.4 on 2026-05-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vestoapp', '0004_delete_investimento_transacao_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='categoria',
            field=models.CharField(choices=[('alimentacao', 'Alimentação'), ('transporte', 'Transporte'), ('moradia', 'Moradia'), ('saude', 'Saúde'), ('educacao', 'Educação'), ('lazer', 'Lazer'), ('investimentos', 'Investimentos'), ('salario', 'Salário'), ('vendas', 'Vendas'), ('outros', 'Outros')], default='outros', max_length=30),
        ),
    ]
