# Generated by Django 6.0.4 on 2026-06-07 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vestoapp', '0006_transacao_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('ticker', models.CharField(blank=True, max_length=20)),
                ('tipo', models.CharField(choices=[('acao', 'Acao'), ('fii', 'FII'), ('renda_fixa', 'Renda Fixa'), ('cripto', 'Cripto'), ('outros', 'Outros')], max_length=20)),
                ('instituicao', models.CharField(blank=True, max_length=80)),
                ('quantidade', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('preco_medio', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('preco_atual', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investimentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoInvestimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('compra', 'Compra'), ('venda', 'Venda'), ('rendimento', 'Rendimento')], max_length=15)),
                ('quantidade', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('data', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='vestoapp.investimento')),
            ],
            options={
                'ordering': ['-data', '-created_at'],
            },
        ),
    ]
