# Generated by Django 6.0.4 on 2026-06-07 03:12

from django.db import migrations, models


def mover_transacoes_para_outros(apps, schema_editor):
    Transacao = apps.get_model("vestoapp", "Transacao")
    Transacao.objects.filter(categoria="investimentos").update(categoria="outros")


class Migration(migrations.Migration):

    dependencies = [
        ('vestoapp', '0007_investimento_movimentacaoinvestimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacaoinvestimento',
            name='investimento',
        ),
        migrations.RunPython(mover_transacoes_para_outros, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='transacao',
            name='categoria',
            field=models.CharField(choices=[('alimentacao', 'Alimentação'), ('transporte', 'Transporte'), ('moradia', 'Moradia'), ('saude', 'Saúde'), ('educacao', 'Educação'), ('lazer', 'Lazer'), ('salario', 'Salário'), ('vendas', 'Vendas'), ('outros', 'Outros')], default='outros', max_length=30),
        ),
        migrations.DeleteModel(
            name='Investimento',
        ),
        migrations.DeleteModel(
            name='MovimentacaoInvestimento',
        ),
    ]
