# Generated by Django 6.0.4 on 2026-06-07 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vestoapp', '0009_preferenciausuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransacaoRecorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=120)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saida')], max_length=10)),
                ('categoria', models.CharField(choices=[('alimentacao', 'Alimentacao'), ('transporte', 'Transporte'), ('moradia', 'Moradia'), ('saude', 'Saude'), ('educacao', 'Educacao'), ('lazer', 'Lazer'), ('salario', 'Salario'), ('vendas', 'Vendas'), ('outros', 'Outros')], default='outros', max_length=30)),
                ('dia_do_mes', models.PositiveSmallIntegerField()),
                ('ativa', models.BooleanField(default=True)),
                ('proxima_data', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes_recorrentes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='transacao',
            name='recorrencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes_geradas', to='vestoapp.transacaorecorrente'),
        ),
        migrations.AddConstraint(
            model_name='transacao',
            constraint=models.UniqueConstraint(fields=('recorrencia', 'data'), name='transacao_recorrente_unica_por_data'),
        ),
    ]
